const ADD_TO_DO = "TO_DO_LIST/ADD_TO_DO";
const UPDATE_COMPLETED = "TO_DO_LIST/UPDATE_COMPLETED";

// Filters
const FILTER_SEARCH = "FILTERS/SEARCH";
const FILTER_PRIORIRY = "FILTERS/PRIORIRY";
const FILTER_COMPLETED = "FILTERS/COMPLETED";

export {
  ADD_TO_DO,
  FILTER_SEARCH,
  FILTER_PRIORIRY,
  FILTER_COMPLETED,
  UPDATE_COMPLETED,
};
